/**
 * API endpoint paths for the FixMyText backend.
 * Used with RTK Query's transformText mutation.
 */

export const ENDPOINTS = {
  // Transform
  UPPERCASE: '/api/v1/text/uppercase',
  LOWERCASE: '/api/v1/text/lowercase',
  INVERSE_CASE: '/api/v1/text/inversecase',
  SENTENCE_CASE: '/api/v1/text/sentencecase',
  TITLE_CASE: '/api/v1/text/titlecase',
  UPPER_CAMEL_CASE: '/api/v1/text/upper-camel-case',
  LOWER_CAMEL_CASE: '/api/v1/text/lower-camel-case',
  SNAKE_CASE: '/api/v1/text/snake-case',
  KEBAB_CASE: '/api/v1/text/kebab-case',
  CAPITALIZE_WORDS: '/api/v1/text/capitalize-words',
  ALTERNATING_CASE: '/api/v1/text/alternating-case',
  INVERSE_WORD_CASE: '/api/v1/text/inverse-word-case',
  WIDE_TEXT: '/api/v1/text/wide-text',
  SMALL_CAPS: '/api/v1/text/small-caps',
  UPSIDE_DOWN: '/api/v1/text/upside-down',
  STRIKETHROUGH: '/api/v1/text/strikethrough',
  AP_TITLE_CASE: '/api/v1/text/ap-title-case',
  SWAP_WORD_CASE: '/api/v1/text/swap-word-case',
  DOT_CASE: '/api/v1/text/dot-case',
  CONSTANT_CASE: '/api/v1/text/constant-case',
  TRAIN_CASE: '/api/v1/text/train-case',
  PATH_CASE: '/api/v1/text/path-case',
  FLAT_CASE: '/api/v1/text/flat-case',
  COBOL_CASE: '/api/v1/text/cobol-case',

  // Text Cleanup
  REMOVE_EXTRA_SPACES: '/api/v1/text/remove-extra-spaces',
  REMOVE_ALL_SPACES: '/api/v1/text/remove-all-spaces',
  REMOVE_LINE_BREAKS: '/api/v1/text/remove-line-breaks',
  STRIP_HTML: '/api/v1/text/strip-html',
  REMOVE_ACCENTS: '/api/v1/text/remove-accents',
  TOGGLE_SMART_QUOTES: '/api/v1/text/toggle-smart-quotes',
  STRIP_INVISIBLE: '/api/v1/text/strip-invisible',
  STRIP_EMOJI: '/api/v1/text/strip-emoji',
  NORMALIZE_WHITESPACE: '/api/v1/text/normalize-whitespace',
  STRIP_NON_ASCII: '/api/v1/text/strip-non-ascii',
  FIX_LINE_ENDINGS: '/api/v1/text/fix-line-endings',
  STRIP_MARKDOWN: '/api/v1/text/strip-markdown',
  TRIM_LINES: '/api/v1/text/trim-lines',
  STRIP_EMPTY_LINES: '/api/v1/text/strip-empty-lines',
  STRIP_URLS: '/api/v1/text/strip-urls',
  STRIP_EMAILS: '/api/v1/text/strip-emails',
  NORMALIZE_PUNCTUATION: '/api/v1/text/normalize-punctuation',
  STRIP_NUMBERS: '/api/v1/text/strip-numbers',

  // Encoding
  BASE64_ENCODE: '/api/v1/text/base64-encode',
  BASE64_DECODE: '/api/v1/text/base64-decode',
  URL_ENCODE: '/api/v1/text/url-encode',
  URL_DECODE: '/api/v1/text/url-decode',
  HEX_ENCODE: '/api/v1/text/hex-encode',
  HEX_DECODE: '/api/v1/text/hex-decode',
  MORSE_ENCODE: '/api/v1/text/morse-encode',
  MORSE_DECODE: '/api/v1/text/morse-decode',

  // Text Tools
  REVERSE: '/api/v1/text/reverse',
  SORT_LINES_ASC: '/api/v1/text/sort-lines-asc',
  SORT_LINES_DESC: '/api/v1/text/sort-lines-desc',
  REMOVE_DUPLICATE_LINES: '/api/v1/text/remove-duplicate-lines',
  REVERSE_LINES: '/api/v1/text/reverse-lines',
  NUMBER_LINES: '/api/v1/text/number-lines',
  SHUFFLE_LINES: '/api/v1/text/shuffle-lines',
  SORT_BY_LENGTH: '/api/v1/text/sort-by-length',
  SORT_NUMERIC: '/api/v1/text/sort-numeric',
  LINE_FREQUENCY: '/api/v1/text/line-frequency',
SPLIT_TO_LINES: '/api/v1/text/split-to-lines',
  JOIN_LINES: '/api/v1/text/join-lines',
  PAD_LINES: '/api/v1/text/pad-lines',
  WRAP_LINES: '/api/v1/text/wrap-lines',
  FILTER_LINES: '/api/v1/text/filter-lines',
  REMOVE_LINES: '/api/v1/text/remove-lines',
  TRUNCATE_LINES: '/api/v1/text/truncate-lines',
  EXTRACT_NTH_LINES: '/api/v1/text/extract-nth-lines',
  ROT13: '/api/v1/text/rot13',

  // Binary / Octal / Decimal
  BINARY_ENCODE: '/api/v1/text/binary-encode',
  BINARY_DECODE: '/api/v1/text/binary-decode',
  OCTAL_ENCODE: '/api/v1/text/octal-encode',
  OCTAL_DECODE: '/api/v1/text/octal-decode',
  DECIMAL_ENCODE: '/api/v1/text/decimal-encode',
  DECIMAL_DECODE: '/api/v1/text/decimal-decode',

  // Unicode Escape
  UNICODE_ESCAPE: '/api/v1/text/unicode-escape',
  UNICODE_UNESCAPE: '/api/v1/text/unicode-unescape',

  // Brainfuck
  BRAINFUCK_ENCODE: '/api/v1/text/brainfuck-encode',
  BRAINFUCK_DECODE: '/api/v1/text/brainfuck-decode',

  // Ciphers
  ATBASH: '/api/v1/text/atbash',
  CAESAR_CIPHER: '/api/v1/text/caesar-cipher',
  RAIL_FENCE_ENC: '/api/v1/text/rail-fence-encrypt',
  RAIL_FENCE_DEC: '/api/v1/text/rail-fence-decrypt',
  CAESAR_BRUTE_FORCE: '/api/v1/text/caesar-brute-force',
  NATO_PHONETIC: '/api/v1/text/nato-phonetic',
  BACON_CIPHER: '/api/v1/text/bacon-cipher',
  VIGENERE_ENC: '/api/v1/text/vigenere-encrypt',
  VIGENERE_DEC: '/api/v1/text/vigenere-decrypt',
  PLAYFAIR_ENC: '/api/v1/text/playfair-encrypt',
  SUBSTITUTION_CIPHER: '/api/v1/text/substitution-cipher',
  COLUMNAR_TRANSPOSITION: '/api/v1/text/columnar-transposition',

  // Encoding Extensions
  BASE32_ENCODE: '/api/v1/text/base32-encode',
  BASE32_DECODE: '/api/v1/text/base32-decode',
  ASCII85_ENCODE: '/api/v1/text/ascii85-encode',
  ASCII85_DECODE: '/api/v1/text/ascii85-decode',

  // Escape / Unescape
  JSON_ESCAPE: '/api/v1/text/json-escape',
  JSON_UNESCAPE: '/api/v1/text/json-unescape',
  HTML_ESCAPE: '/api/v1/text/html-escape',
  HTML_UNESCAPE: '/api/v1/text/html-unescape',

  // Developer Tools
  FORMAT_JSON: '/api/v1/text/format-json',
  JSON_TO_YAML: '/api/v1/text/json-to-yaml',
  CSV_TO_JSON: '/api/v1/text/csv-to-json',
  JSON_TO_CSV: '/api/v1/text/json-to-csv',
  XML_TO_JSON: '/api/v1/text/xml-to-json',
  CSV_TO_TABLE: '/api/v1/text/csv-to-table',
  SQL_INSERT_GEN: '/api/v1/text/sql-insert-gen',

  // AI Writing (new)
  ACADEMIC_STYLE: '/api/v1/text/academic-style',
  CREATIVE_STYLE: '/api/v1/text/creative-style',
  TECHNICAL_STYLE: '/api/v1/text/technical-style',
  ACTIVE_VOICE: '/api/v1/text/active-voice',
  REDUNDANCY_REMOVER: '/api/v1/text/redundancy-remover',
  SENTENCE_SPLITTER: '/api/v1/text/sentence-splitter',
  CONCISENESS: '/api/v1/text/conciseness',
  RESUME_BULLETS: '/api/v1/text/resume-bullets',
  MEETING_NOTES: '/api/v1/text/meeting-notes',
  COVER_LETTER: '/api/v1/text/cover-letter',
  OUTLINE_TO_DRAFT: '/api/v1/text/outline-to-draft',
  CONTINUE_WRITING: '/api/v1/text/continue-writing',
  REWRITE_UNIQUE: '/api/v1/text/rewrite-unique',
  TONE_ANALYZER: '/api/v1/text/tone-analyzer',

  // AI Content (new)
  LINKEDIN_POST: '/api/v1/text/linkedin-post',
  TWITTER_THREAD: '/api/v1/text/twitter-thread',
  INSTAGRAM_CAPTION: '/api/v1/text/instagram-caption',
  YOUTUBE_DESC: '/api/v1/text/youtube-description',
  SOCIAL_BIO: '/api/v1/text/social-bio',
  PRODUCT_DESC: '/api/v1/text/product-description',
  CTA_GENERATOR: '/api/v1/text/cta-generator',
  AD_COPY: '/api/v1/text/ad-copy',
  LANDING_HEADLINE: '/api/v1/text/landing-headline',
  EMAIL_SUBJECT: '/api/v1/text/email-subject',
  CONTENT_IDEAS: '/api/v1/text/content-ideas',
  HOOK_GENERATOR: '/api/v1/text/hook-generator',
  ANGLE_GENERATOR: '/api/v1/text/angle-generator',
  FAQ_SCHEMA: '/api/v1/text/faq-schema',

  // Language (new)
  POS_TAGGER: '/api/v1/text/pos-tagger',
  SENTENCE_TYPE: '/api/v1/text/sentence-type',
  GRAMMAR_EXPLAIN: '/api/v1/text/grammar-explain',
  SYNONYM_FINDER: '/api/v1/text/synonym-finder',
  ANTONYM_FINDER: '/api/v1/text/antonym-finder',
  DEFINE_WORDS: '/api/v1/text/define-words',
  WORD_POWER: '/api/v1/text/word-power',
  VOCAB_COMPLEXITY: '/api/v1/text/vocab-complexity',
  JARGON_SIMPLIFIER: '/api/v1/text/jargon-simplifier',
  FORMALITY_DETECTOR: '/api/v1/text/formality-detector',
  CLICHE_DETECTOR: '/api/v1/text/cliche-detector',

  // Generator (new)
  REGEX_GEN: '/api/v1/text/regex-generator',
  WRITING_PROMPT: '/api/v1/text/writing-prompt',
  TEAM_NAME_GEN: '/api/v1/text/team-name-generator',
  MOCK_API_RESPONSE: '/api/v1/text/mock-api-response',

  // AI Tools
  GENERATE_HASHTAGS: '/api/v1/text/generate-hashtags',
  GENERATE_SEO_TITLES: '/api/v1/text/generate-seo-titles',
  GENERATE_META_DESCRIPTIONS: '/api/v1/text/generate-meta-descriptions',
  GENERATE_BLOG_OUTLINE: '/api/v1/text/generate-blog-outline',
  SHORTEN_FOR_TWEET: '/api/v1/text/shorten-for-tweet',
  REWRITE_EMAIL: '/api/v1/text/rewrite-email',
  EXTRACT_KEYWORDS: '/api/v1/text/extract-keywords',
  TRANSLATE: '/api/v1/text/translate',
  TRANSLITERATE: '/api/v1/text/transliterate',
  EMOJIFY: '/api/v1/text/emojify',
  DETECT_LANGUAGE: '/api/v1/text/detect-language',
  SUMMARIZE: '/api/v1/text/summarize',
  FIX_GRAMMAR: '/api/v1/text/fix-grammar',
  PARAPHRASE: '/api/v1/text/paraphrase',
  CHANGE_TONE: '/api/v1/text/change-tone',
  ANALYZE_SENTIMENT: '/api/v1/text/analyze-sentiment',
  LENGTHEN_TEXT: '/api/v1/text/lengthen-text',
  ELI5: '/api/v1/text/eli5',
  PROOFREAD: '/api/v1/text/proofread',
  GENERATE_TITLE: '/api/v1/text/generate-title',
  REFACTOR_PROMPT: '/api/v1/text/refactor-prompt',
  CHANGE_FORMAT: '/api/v1/text/change-format',
}
